# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  # OR specify logs bucket:
  logsBucket: 'gs://focused-pipe-479715-s8-cloudbuild-logs'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tsateng-productions:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tsateng-productions:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tsateng-productions'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tsateng-productions:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/tsateng-productions:$COMMIT_SHA'
